use slimmer docker image
restatedev/dev-tools pull request #10
Opened 2024-09-06 18:42 UTC by aradwann

improvements: 
Layer Reduction: Combined RUN commands where appropriate.
Smaller Base Image: Used bookworm-slim as the base to reduce image size.
Removed Unnecessary Packages: Used --no-install-recommends to install only necessary packages, avoiding bloated images.

might help a little bit in resolving https://github.com/restatedev/dev-tools/issues/7

2024-10-14 17:26 UTC, jackkleeman approved these changes
Thanks for your contribution! This looks great

2024-10-14 17:28 UTC, jackkleeman requested changes
actually, i can see that the linker script for musl compilation is no longer present. is this deliberate? does this still work for musl builds?

2024-10-15 07:05 UTC, aradwann commented
> actually, i can see that the linker script for musl compilation is no longer present. is this deliberate? does this still work for musl builds?

after reorganising  the dockerfile I wanted to see if it would work without linking the licstdc++, but there is no pipeline here to verify, so I restored it

2024-10-15 08:11 UTC, jackkleeman commented
nice! I'll merge and check if a binary build still works over in the main repo

2024-10-15 08:11 UTC, merged

2024-10-15 09:34 UTC, aradwann commented
GH in this repo 

before 
![image](https://github.com/user-attachments/assets/830acd71-9c0f-4d3c-b106-8c9c5df80c92)

after 
![Screenshot from 2024-10-15 12-31-05](https://github.com/user-attachments/assets/00e7810b-61dc-438b-bd7c-503df6cab0fc)

that's a good sign!

2024-10-15 09:44 UTC, jackkleeman commented
haha, thats actually because we updated the docker.yml over in the main repo to use a much beefier actions runner

2024-10-15 16:02 UTC, jackkleeman commented
OK, i had to add build-essential but otherwise seems to work. thanks again